[tasks.setup]
description = "Setup project"
run = ["hk install"]

[tasks.build]
description = "Build hermes binary"
run = "go build -o ./hermes ./cmd/hermes/"

[tasks.test]
description = "Run unit tests"
run = "go test ./..."

[tasks.run]
description = "Run hermes CLI (dev mode)"
run = "go run ./cmd/hermes/ $@"
